import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import React, { useState } from "react";

export default function Home() {
	const [bgPrice, setBgPrice] = useState(0);
	const [dePriceLv, setDePriceLv] = useState(0);
	const [komisionna, setKomisionna] = useState(0);
	const [kg, setKg] = useState(0);
	const [cena, setCena] = useState(0);
	const [razlika, setRazlika] = useState(0);

	const onBgChange = (event) => {
		setBgPrice(event.target.value);
	};

	const onDeChange = (event) => {
		setDePriceLv(event.target.value * 1.95583);
		setKomisionna(dePriceLv / 10);
	};

	const onKgChange = (event) => {
		setKg(event.target.value * 4);
	};

	const onSubmit = (event) => {
		setCena(dePriceLv + komisionna + kg);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Сметни си сам</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Калкулатор за разлика в цената при поръчка от Германия!</h1>
				<div className={styles.main.bgprice}>
					<label>Цена в България: </label><br/>
					<input
						type="text"
						id="bgprice"
						name="bgprice"
						onChange={onBgChange}
					/>
					BGN
				</div>
				<div className={styles.main.deprice}>
					<label>Цена в Германия: </label><br/>
					<input
						type="text"
						id="deprice"
						name="deprice"
						onChange={onDeChange}
					/>
					€
				</div>
				<div className={styles.main.kg}>
					<label>Тегло: </label><br/>
					<input type="text" id="teglo" name="teglo" onChange={onKgChange} /> kg
				</div>
				<button type="submit" value="Submit" onClick={onSubmit}>
					Изчисли
				</button>
				<p>Цена в лева: {dePriceLv.toFixed(2)} лв</p>
				<p>Комисионна 10%: {komisionna.toFixed(2)} лв</p>
				<p>Доставка до София 4лв/кг: {kg.toFixed(2)} лв</p>
				<p>Крайна цена от Германия: {cena.toFixed(2)} лв</p>
				<p>
					Разлика:{" "}
					{(bgPrice - cena > 0 && bgPrice - cena != bgPrice
						? bgPrice - cena
						: 0
					).toFixed(2)}{" "}
					лв (спестени)
				</p>
			</main>
		</div>
	);
}
